<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class catalogopartidas_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('catalogopatidas')->insert(['Concepto' => 1200, 'NombrePartida' => 'SUELDOS BASE AL PERSONAL EVENTUAL', 'Partida' => 1212]);
        DB::table('catalogopatidas')->insert(['Concepto' => 1400, 'NombrePartida' => 'APORTACIONES PARA SEGUROS', 'Partida' => 1440]);
        DB::table('catalogopatidas')->insert(['Concepto' => 1500, 'NombrePartida' => 'PRESTACIONES CONTRACTUALES', 'Partida' => 1540]);
        DB::table('catalogopatidas')->insert(['Concepto' => 1500, 'NombrePartida' => 'APOYOS A LA CAPACITACIÓN DE LOS SERVIDORES PÚBLICOS', 'Partida' => 1550]);
        DB::table('catalogopatidas')->insert(['Concepto' => 1500, 'NombrePartida' => 'OTRAS PRESTACIONES SOCIALES Y ECONÓMICAS', 'Partida' => 1590]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIALES, UTILES Y EQUIPOS MENORES DE OFICINA', 'Partida' => 2110]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIALES Y UTILES DE IMPRESION Y REPRODUCCION', 'Partida' => 2120]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIAL ESTADISTICO Y GEOGRAFICO', 'Partida' => 2130]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIALES, UTILES Y EQUIPOS MENORES DE TECNOLOGIAS DE LA INFORMACION Y COMUNICACIONES', 'Partida' => 2140]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIAL IMPRESO E INFORMACION DIGITAL', 'Partida' => 2150]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIAL DE LIMPIEZA', 'Partida' => 2160]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIALES Y UTILES DE ENSEÑANZA', 'Partida' => 2170]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2100, 'NombrePartida' => 'MATERIALES PARA EL REGISTRO E IDENTIFICACION DE BIENES Y PERSONAS', 'Partida' => 2180]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2200, 'NombrePartida' => 'PRODUCTOS ALIMENTICIOS PARA PERSONAS', 'Partida' => 2210]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2200, 'NombrePartida' => 'PRODUCTOS ALIMENTICIOS PARA ANIMALES', 'Partida' => 2220]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2200, 'NombrePartida' => 'UTENSILIOS PARA EL SERVICIO DE ALIMENTACION', 'Partida' => 2230]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'PRODUCTOS ALIMENTICIOS, AGROPECUARIOS Y FORESTALES ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2310]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'INSUMOS TEXTILES ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2320]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'PRODUCTOS DE PAPEL, CARTON E IMPRESOS ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2330]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'COMBUSTIBLES, LUBRICANTES, ADITIVOS, CARBON Y SUS DERIVADOS ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2340]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'PRODUCTOS QUIMICOS, FARMACEUTICOS Y DE LABORATORIO ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2350]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'PRODUCTOS METALICOS Y A BASE DE MINERALES NO METALICOS ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2360]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'PRODUCTOS DE CUERO, PIEL, PLASTICO Y HULE ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2370]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'MERCANCIAS ADQUIRIDAS PARA SU COMERCIALIZACION', 'Partida' => 2380]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2300, 'NombrePartida' => 'OTROS PRODUCTOS ADQUIRIDOS COMO MATERIA PRIMA', 'Partida' => 2390]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'PRODUCTOS MINERALES NO METALICOS', 'Partida' => 2410]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'CEMENTO Y PRODUCTOS DE CONCRETO', 'Partida' => 2420]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'CAL, YESO Y PRODUCTOS DE YESO', 'Partida' => 2430]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'MADERA Y PRODUCTOS DE MADERA', 'Partida' => 2440]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'VIDRIO Y PRODUCTOS DE VIDRIO', 'Partida' => 2450]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'MATERIAL ELECTRICO Y ELECTRONICO', 'Partida' => 2460]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'ARTICULOS METALICOS PARA LA CONSTRUCCION', 'Partida' => 2470]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'MATERIALES COMPLEMENTARIOS', 'Partida' => 2480]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2400, 'NombrePartida' => 'OTROS MATERIALES Y ARTICULOS DE CONSTRUCCION Y REPARACION', 'Partida' => 2490]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'PRODUCTOS QUIMICOS BASICOS', 'Partida' => 2510]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'FERTILIZANTES, PESTICIDAS Y OTROS AGROQUIMICOS', 'Partida' => 2520]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'MEDICINAS Y PRODUCTOS FARMACEUTICOS', 'Partida' => 2530]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'MATERIALES, ACCESORIOS Y SUMINISTROS MEDICOS', 'Partida' => 2540]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'MATERIALES, ACCESORIOS Y SUMINISTROS DE LABORATORIO', 'Partida' => 2550]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'FIBRAS SINTETICAS, HULES, PLASTICOS Y DERIVADOS', 'Partida' => 2560]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2500, 'NombrePartida' => 'OTROS PRODUCTOS QUIMICOS', 'Partida' => 2590]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2600, 'NombrePartida' => 'COMBUSTIBLES, LUBRICANTES Y ADITIVOS', 'Partida' => 2610]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2700, 'NombrePartida' => 'VESTUARIO Y UNIFORMES', 'Partida' => 2710]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2700, 'NombrePartida' => 'PRENDAS DE SEGURIDAD Y PROTECCION PERSONAL', 'Partida' => 2720]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2700, 'NombrePartida' => 'ARTICULOS DEPORTIVOS', 'Partida' => 2730]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2700, 'NombrePartida' => 'PRODUCTOS TEXTILES', 'Partida' => 2740]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2700, 'NombrePartida' => 'BLANCOS Y OTROS PRODUCTOS TEXTILES, EXCEPTO PRENDAS DE VESTIR', 'Partida' => 2750]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2800, 'NombrePartida' => 'SUSTANCIAS Y MATERIALES EXPLOSIVOS', 'Partida' => 2810]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2800, 'NombrePartida' => 'MATERIALES DE SEGURIDAD PUBLICA', 'Partida' => 2820]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2800, 'NombrePartida' => 'PRENDAS DE PROTECCION PARA SEGURIDAD PUBLICA Y NACIONAL', 'Partida' => 2830]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'HERRAMIENTAS MENORES', 'Partida' => 2910]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE EDIFICIOS', 'Partida' => 2920]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE MOBILIARIO Y EQUIPO DE ADMINISTRACION, EDUCACIONAL Y RECREATIVO', 'Partida' => 2930]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE EQUIPO DE COMPUTO Y TECNOLOGIAS DE LA INFORMACION', 'Partida' => 2940]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE EQUIPO E INSTRUMENTAL MEDICO Y DE LABORATORIO', 'Partida' => 2950]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE EQUIPO DE TRANSPORTE', 'Partida' => 2960]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE EQUIPO DE DEFENSA Y SEGURIDAD', 'Partida' => 2970]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES DE MAQUINARIA Y OTROS EQUIPOS', 'Partida' => 2980]);
        DB::table('catalogopatidas')->insert(['Concepto' => 2900, 'NombrePartida' => 'REFACCIONES Y ACCESORIOS MENORES OTROS BIENES MUEBLES', 'Partida' => 2990]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'ENERGIA ELECTRICA', 'Partida' => 3110]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'GAS', 'Partida' => 3120]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'AGUA', 'Partida' => 3130]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'TELEFONIA TRADICIONAL', 'Partida' => 3140]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'TELEFONIA CELULAR', 'Partida' => 3150]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'SERVICIOS DE TELECOMUNICACIONES Y SATELITES', 'Partida' => 3160]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'SERVICIOS DE ACCESO DE INTERNET, REDES Y PROCESAMIENTO DE INFORMACION', 'Partida' => 3170]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'SERVICIOS POSTALES Y TELEGRAFICOS', 'Partida' => 3180]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3100, 'NombrePartida' => 'SERVICIOS INTEGRALES Y OTROS SERVICIOS', 'Partida' => 3190]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE EDIFICIOS', 'Partida' => 3220]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE MOBILIARIO Y EQUIPO DE ADMINISTRACION, EDUCACIONAL Y RECREATIVO', 'Partida' => 3230]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE EQUIPO E INSTRUMENTAL MEDICO Y DE LABORATORIO', 'Partida' => 3240]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE EQUIPO DE TRANSPORTE', 'Partida' => 3250]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE MAQUINARIA, OTROS EQUIPOS Y HERRAMIENTAS', 'Partida' => 3260]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'ARRENDAMIENTO DE ACTIVOS INTANGIBLES', 'Partida' => 3270]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3200, 'NombrePartida' => 'OTROS ARRENDAMIENTOS', 'Partida' => 3290]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS LEGALES, DE CONTABILIDAD, AUDITORIA Y RELACIONADOS', 'Partida' => 3310]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE DISEÑO, ARQUITECTURA, INGENIERIA Y ACTIVIDADES RELACIONADAS', 'Partida' => 3320]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE CONSULTORIA ADMINISTRATIVA, PROCESOS, TECNICA Y EN TECNOLOGIAS DE LA INFORMACION', 'Partida' => 3330]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE CAPACITACION', 'Partida' => 3340]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE INVESTIGACION CIENTIFICA Y DESARROLLO', 'Partida' => 3350]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE APOYO ADMINISTRATIVO, TRADUCCION, FOTOCOPIADO E IMPRESION', 'Partida' => 3360]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE PROTECCION Y SEGURIDAD', 'Partida' => 3370]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS DE VIGILANCIA', 'Partida' => 3380]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3300, 'NombrePartida' => 'SERVICIOS PROFESIONALES, CIENTIFICOS Y TECNICOS INTEGRALES', 'Partida' => 3390]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'SERVICIOS FINANCIEROS Y BANCARIOS', 'Partida' => 3410]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'SERVICIOS DE RECAUDACION, TRASLADO Y CUSTODIA DE VALORES', 'Partida' => 3430]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'SEGUROS DE RESPONSABILIDAD PATRIMONIAL Y FIANZAS', 'Partida' => 3440]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'SEGURO DE BIENES PATRIMONIALES', 'Partida' => 3450]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'ALMACENAJE, ENVASE Y EMBALAJE', 'Partida' => 3460]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3400, 'NombrePartida' => 'FLETES Y MANIOBRAS', 'Partida' => 3470]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'CONSERVACION Y MANTENIMIENTO MENOR DE INMUEBLES', 'Partida' => 3510]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'INSTALACION, REPARACION Y MANTENIMIENTO DE MOBILIARIO Y EQUIPO DE ADMINISTRACION, EDUCACIONAL Y RECREATIVO', 'Partida' => 3520]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'INSTALACION, REPARACION Y MANTENIMIENTO DE EQUIPO DE COMPUTO Y TECNOLOGIA DE LA INFORMACION', 'Partida' => 3530]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'INSTALACION, REPARACION Y MANTENIMIENTO DE EQUIPO E INSTRUMENTAL MEDICO Y DE LABORATORIO', 'Partida' => 3540]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'REPARACION Y MANTENIMIENTO DE EQUIPO DE TRANSPORTE', 'Partida' => 3550]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'REPARACION Y MANTENIMIENTO DE EQUIPO DE DEFENSA Y SEGURIDAD', 'Partida' => 3560]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'INSTALACION, REPARACION Y MANTENIMIENTO DE MAQUINARIA, OTROS EQUIPOS Y HERRAMIENTA', 'Partida' => 3570]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'SERVICIOS DE LIMPIEZA Y MANEJO DE DESECHOS', 'Partida' => 3580]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3500, 'NombrePartida' => 'SERVICIOS DE JARDINERIA Y FUMIGACION', 'Partida' => 3590]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'DIFUSION POR RADIO, TELEVISION Y OTROS MEDIOS DE MENSAJES SOBRE PROGRAMAS Y ACTIVIDADES GUBERNAMENTALES', 'Partida' => 3610]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'DIFUSION POR RADIO, TELEVISION Y OTROS MEDIOS DE MENSAJES COMERCIALES PARA PROMOVER LA VENTA DE BIENES O SERVICIOS', 'Partida' => 3620]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'SERVICIOS DE CREATIVIDAD, PREPRODUCCION Y PRODUCCION DE PUBLICIDAD, EXCEPTO INTERNET', 'Partida' => 3630]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'SERVICIOS DE REVELADO DE FOTOGRAFIAS', 'Partida' => 3640]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'SERVICIOS DE LA INDUSTRIA FILMICA, DEL SONIDO Y DEL VIDEO', 'Partida' => 3650]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'SERVICIO DE CREACION Y DIFUSION DE CONTENIDO EXCLUSIVAMENTE A TRAVES DE INTERNET', 'Partida' => 3660]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3600, 'NombrePartida' => 'OTROS SERVICIOS DE INFORMACION', 'Partida' => 3690]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'PASAJES AEREOS', 'Partida' => 3710]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'PASAJES TERRESTRES', 'Partida' => 3720]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'PASAJES MARITIMOS, LACUSTRES Y FLUVIALES', 'Partida' => 3730]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'VIATICOS EN EL PAIS', 'Partida' => 3750]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'VIATICOS EN EL EXTRANJERO', 'Partida' => 3760]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'GASTOS DE INSTALACION Y TRASLADO DE MENAJE', 'Partida' => 3770]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'SERVICIOS INTEGRALES DE TRASLADO Y VIATICOS', 'Partida' => 3780]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3700, 'NombrePartida' => 'OTROS SERVICIOS DE TRASLADO Y HOSPEDAJE', 'Partida' => 3790]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3800, 'NombrePartida' => 'GASTOS DE CEREMONIAL', 'Partida' => 3810]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3800, 'NombrePartida' => 'GASTOS DE ORDEN SOCIAL Y CULTURAL', 'Partida' => 3820]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3800, 'NombrePartida' => 'CONGRESOS Y CONVENCIONES', 'Partida' => 3830]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3800, 'NombrePartida' => 'EXPOSICIONES', 'Partida' => 3840]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3800, 'NombrePartida' => 'GASTOS DE REPRESENTACION', 'Partida' => 3850]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3900, 'NombrePartida' => 'SERVICIOS FUNERARIOS Y DE CEMENTERIOS', 'Partida' => 3910]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3900, 'NombrePartida' => 'IMPUESTOS Y DERECHOS', 'Partida' => 3920]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3900, 'NombrePartida' => 'OTROS GASTOS POR RESPONSABILIDADES', 'Partida' => 3960]);
        DB::table('catalogopatidas')->insert(['Concepto' => 3900, 'NombrePartida' => 'OTROS SERVICIOS GENERALES', 'Partida' => 3990]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4100, 'NombrePartida' => 'TRANSFERENCIAS INTERNAS OTORGADAS A ENTIDADES PARAESTATALES NO EMPRESARIALES Y NO FINANCIERAS', 'Partida' => 4150]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4100, 'NombrePartida' => 'TRANSFERENCIAS INTERNAS OTORGADAS A ENTIDADES PARAESTATALES EMPRESARIALES Y NO FINANCIERAS', 'Partida' => 4160]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A LA PRODUCCIÓN', 'Partida' => 4310]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A LA DISTRIBUCIÓN', 'Partida' => 4320]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A LA INVERSIÓN', 'Partida' => 4330]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A LA PRESTACIÓN DE SERVICIOS PÚBLICOS', 'Partida' => 4340]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS PARA CUBRIR DIFERENCIALES DE TASAS DE INTERÉS', 'Partida' => 4350]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A LA VIVIENDA', 'Partida' => 4360]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBVENCIONES AL CONSUMO', 'Partida' => 4370]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'SUBSIDIOS A ENTIDADES FEDERATIVAS Y MUNICIPIOS', 'Partida' => 4380]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4300, 'NombrePartida' => 'OTROS SUBSIDIOS', 'Partida' => 4390]);
        DB::table('catalogopatidas')->insert(['Concepto' => 4400, 'NombrePartida' => 'AYUDAS SOCIALES A PERSONAS', 'Partida' => 4410]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5100, 'NombrePartida' => 'MUEBLES DE OFICINA Y ESTANTERIA', 'Partida' => 5110]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5100, 'NombrePartida' => 'MUEBLES, EXCEPTO DE OFICINA Y ESTANTERIA', 'Partida' => 5120]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5100, 'NombrePartida' => 'BIENES ARTISTICOS, CULTURALES Y CIENTIFICOS', 'Partida' => 5130]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5100, 'NombrePartida' => 'EQUIPO DE COMPUTO Y DE TECNOLOGIAS DE LA INFORMACION', 'Partida' => 5150]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5100, 'NombrePartida' => 'OTROS MOBILIARIOS Y EQUIPOS DE ADMINISTRACION', 'Partida' => 5190]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5200, 'NombrePartida' => 'EQUIPOS Y APARATOS AUDIOVISUALES', 'Partida' => 5210]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5200, 'NombrePartida' => 'APARATOS DEPORTIVOS', 'Partida' => 5220]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5200, 'NombrePartida' => 'CAMARAS FOTOGRAFICAS Y DE VIDEO', 'Partida' => 5230]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5200, 'NombrePartida' => 'OTRO MOBILIARIO Y EQUIPO EDUCACIONAL Y RECREATIVO', 'Partida' => 5290]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5300, 'NombrePartida' => 'EQUIPO MEDICO Y DE LABORATORIO', 'Partida' => 5310]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5300, 'NombrePartida' => 'INSTRUMENTAL MEDICO Y DE LABORATORIO', 'Partida' => 5320]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'VEHICULOS Y EQUIPO TERRESTRE', 'Partida' => 5410]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'CARROCERIAS Y REMOLQUES', 'Partida' => 5420]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'EQUIPO AEROESPACIAL', 'Partida' => 5430]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'EQUIPO FERROVIARIO', 'Partida' => 5440]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'EMBARCACIONES', 'Partida' => 5450]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5400, 'NombrePartida' => 'OTROS EQUIPOS DE TRANSPORTE', 'Partida' => 5490]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5500, 'NombrePartida' => 'EQUIPO DE DEFENSA Y SEGURIDAD', 'Partida' => 5510]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'MAQUINARIA Y EQUIPO AGROPECUARIO', 'Partida' => 5610]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'MAQUINARIA Y EQUIPO INDUSTRIAL', 'Partida' => 5620]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'MAQUINARIA Y EQUIPO DE CONSTRUCCION', 'Partida' => 5630]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'SISTEMAS DE AIRE ACONDICIONADO, CALEFACCION Y DE REFRIGERACION INDUSTRIAL Y COMERCIAL', 'Partida' => 5640]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'EQUIPO DE COMUNICACION Y TELECOMUNICACION', 'Partida' => 5650]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'EQUIPOS DE GENERACION ELECTRICA, APARATOS Y ACCESORIOS ELECTRICOS', 'Partida' => 5660]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'HERRAMIENTAS Y MAQUINAS-HERRAMIENTA', 'Partida' => 5670]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5600, 'NombrePartida' => 'OTROS EQUIPOS', 'Partida' => 5690]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'BOVINOS', 'Partida' => 5710]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'PORCINOS', 'Partida' => 5720]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'OVINOS Y CAPRINOS', 'Partida' => 5740]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'PECES Y ACUICULTURA', 'Partida' => 5750]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'EQUINOS', 'Partida' => 5760]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'ESPECIES MENORES Y DE ZOOLOGICO', 'Partida' => 5770]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5700, 'NombrePartida' => 'ARBOLES Y PLANTAS', 'Partida' => 5780]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5800, 'NombrePartida' => 'OTROS BIENES INMUEBLES', 'Partida' => 5890]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5900, 'NombrePartida' => 'SOFTWARE', 'Partida' => 5910]);
        DB::table('catalogopatidas')->insert(['Concepto' => 5900, 'NombrePartida' => 'LICENCIAS INFORMATICAS E INTELECTUALES', 'Partida' => 5970]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'EDIFICACION NO HABITACIONAL', 'Partida' => 6120]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'CONSTRUCCION DE OBRAS PARA EL ABASTECIMIENTO DE AGUA, PETROLEO, GAS, ELECTRICIDAD Y TELECOMUNICACIONES', 'Partida' => 6130]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'CONSTRUCCION DE VIAS DE COMUNICACION', 'Partida' => 6150]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'OTRAS CONSTRUCCIONES DE INGENIERIA CIVIL U OBRA PESADA', 'Partida' => 6160]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'INSTALACIONES Y EQUIPAMIENTO EN CONSTRUCCIONES', 'Partida' => 6170]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6100, 'NombrePartida' => 'TRABAJOS DE ACABADOS EN EDIFICACIONES Y OTROS TRABAJOS ESPECIALIZADOS', 'Partida' => 6190]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'EDIFICACION HABITACIONAL', 'Partida' => 6210]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'EDIFICACION NO HABITACIONAL', 'Partida' => 6220]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'CONSTRUCCION DE OBRAS PARA EL ABASTECIMIENTO DE AGUA, PETROLEO, GAS, ELECTRICIDAD Y TELECOMUNICACIONES', 'Partida' => 6230]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'DIVISION DE TERRENOS Y CONSTRUCCION DE OBRAS DE URBANIZACION', 'Partida' => 6240]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'CONSTRUCCION DE VIAS DE COMUNICACION', 'Partida' => 6250]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'OTRAS CONSTRUCCIONES DE INGENIERIA CIVIL U OBRA PESADA', 'Partida' => 6260]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'INSTALACIONES Y EQUIPAMIENTO EN CONSTRUCCIONES', 'Partida' => 6270]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6200, 'NombrePartida' => 'TRABAJOS DE ACABADOS EN EDIFICACIONES Y OTROS TRABAJOS ESPECIALIZADOS', 'Partida' => 6290]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6300, 'NombrePartida' => 'ESTUDIOS, FORMULACION Y EVALUACION DE PROYECTOS PRODUCTIVOS NO INCLUIDOS EN CONCEPTOS ANTERIORES DE ESTE CAPITULO', 'Partida' => 6310]);
        DB::table('catalogopatidas')->insert(['Concepto' => 6300, 'NombrePartida' => 'EJECUCION DE PROYECTOS PRODUCTIVOS NO INCLUIDOS EN CONCEPTOS ANTERIORES DE ESTE CAPITULO', 'Partida' => 6320]);
        DB::table('catalogopatidas')->insert(['Concepto' => 8300, 'NombrePartida' => 'APORTACIONES DE LA FEDERACIÓN A LAS ENTIDADES FEDERATIVAS', 'Partida' => 8310]);
    }
}
