<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class catalogotiposmoneda_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 1, 'AbreviaturaTipoMoneda' => 'AED', 'TipoMoneda' => 'Dirham de EAU']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 2, 'AbreviaturaTipoMoneda' => 'AFN', 'TipoMoneda' => 'Afghani']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 3, 'AbreviaturaTipoMoneda' => 'ALL', 'TipoMoneda' => 'Lek']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 4, 'AbreviaturaTipoMoneda' => 'AMD', 'TipoMoneda' => 'Dram armenio']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 5, 'AbreviaturaTipoMoneda' => 'ANG', 'TipoMoneda' => 'Florín antillano neerlandés']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 6, 'AbreviaturaTipoMoneda' => 'AOA', 'TipoMoneda' => 'Kwanza']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 7, 'AbreviaturaTipoMoneda' => 'ARS', 'TipoMoneda' => 'Peso Argentino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 8, 'AbreviaturaTipoMoneda' => 'AUD', 'TipoMoneda' => 'Dólar Australiano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 9, 'AbreviaturaTipoMoneda' => 'AWG', 'TipoMoneda' => 'Aruba Florin']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 10, 'AbreviaturaTipoMoneda' => 'AZN', 'TipoMoneda' => 'Azerbaijanian Manat']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 11, 'AbreviaturaTipoMoneda' => 'BAM', 'TipoMoneda' => 'Convertibles marca']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 12, 'AbreviaturaTipoMoneda' => 'BBD', 'TipoMoneda' => 'Dólar de Barbados']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 13, 'AbreviaturaTipoMoneda' => 'BDT', 'TipoMoneda' => 'Taka']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 14, 'AbreviaturaTipoMoneda' => 'BGN', 'TipoMoneda' => 'Lev búlgaro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 15, 'AbreviaturaTipoMoneda' => 'BHD', 'TipoMoneda' => 'Dinar de Bahrein']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 16, 'AbreviaturaTipoMoneda' => 'BIF', 'TipoMoneda' => 'Burundi Franc']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 17, 'AbreviaturaTipoMoneda' => 'BMD', 'TipoMoneda' => 'Dólar de Bermudas']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 18, 'AbreviaturaTipoMoneda' => 'BND', 'TipoMoneda' => 'Dólar de Brunei']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 19, 'AbreviaturaTipoMoneda' => 'BOB', 'TipoMoneda' => 'Boliviano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 20, 'AbreviaturaTipoMoneda' => 'BOV', 'TipoMoneda' => 'Mvdol']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 21, 'AbreviaturaTipoMoneda' => 'BRL', 'TipoMoneda' => 'Real brasileño']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 22, 'AbreviaturaTipoMoneda' => 'BSD', 'TipoMoneda' => 'Dólar de las Bahamas']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 23, 'AbreviaturaTipoMoneda' => 'BTN', 'TipoMoneda' => 'Ngultrum']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 24, 'AbreviaturaTipoMoneda' => 'BWP', 'TipoMoneda' => 'Pula']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 25, 'AbreviaturaTipoMoneda' => 'BYR', 'TipoMoneda' => 'Rublo bielorruso']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 26, 'AbreviaturaTipoMoneda' => 'BZD', 'TipoMoneda' => 'Dólar de Belice']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 27, 'AbreviaturaTipoMoneda' => 'CAD', 'TipoMoneda' => 'Dolar Canadiense']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 28, 'AbreviaturaTipoMoneda' => 'CDF', 'TipoMoneda' => 'Franco congoleño']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 29, 'AbreviaturaTipoMoneda' => 'CHE', 'TipoMoneda' => 'WIR Euro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 30, 'AbreviaturaTipoMoneda' => 'CHF', 'TipoMoneda' => 'Franco Suizo']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 31, 'AbreviaturaTipoMoneda' => 'CHW', 'TipoMoneda' => 'Franc WIR']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 32, 'AbreviaturaTipoMoneda' => 'CLF', 'TipoMoneda' => 'Unidad de Fomento']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 33, 'AbreviaturaTipoMoneda' => 'CLP', 'TipoMoneda' => 'Peso chileno']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 34, 'AbreviaturaTipoMoneda' => 'CNY', 'TipoMoneda' => 'Yuan Renminbi']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 35, 'AbreviaturaTipoMoneda' => 'COP', 'TipoMoneda' => 'Peso Colombiano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 36, 'AbreviaturaTipoMoneda' => 'COU', 'TipoMoneda' => 'Unidad de Valor real']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 37, 'AbreviaturaTipoMoneda' => 'CRC', 'TipoMoneda' => 'Colón costarricense']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 38, 'AbreviaturaTipoMoneda' => 'CUC', 'TipoMoneda' => 'Peso Convertible']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 39, 'AbreviaturaTipoMoneda' => 'CUP', 'TipoMoneda' => 'Peso Cubano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 40, 'AbreviaturaTipoMoneda' => 'CVE', 'TipoMoneda' => 'Cabo Verde Escudo']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 41, 'AbreviaturaTipoMoneda' => 'CZK', 'TipoMoneda' => 'Corona checa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 42, 'AbreviaturaTipoMoneda' => 'DJF', 'TipoMoneda' => 'Franco de Djibouti']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 43, 'AbreviaturaTipoMoneda' => 'DKK', 'TipoMoneda' => 'Corona danesa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 44, 'AbreviaturaTipoMoneda' => 'DOP', 'TipoMoneda' => 'Peso Dominicano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 45, 'AbreviaturaTipoMoneda' => 'DZD', 'TipoMoneda' => 'Dinar argelino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 46, 'AbreviaturaTipoMoneda' => 'EGP', 'TipoMoneda' => 'Libra egipcia']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 47, 'AbreviaturaTipoMoneda' => 'ERN', 'TipoMoneda' => 'Nakfa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 48, 'AbreviaturaTipoMoneda' => 'ETB', 'TipoMoneda' => 'Birr etíope']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 49, 'AbreviaturaTipoMoneda' => 'EUR', 'TipoMoneda' => 'Euro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 50, 'AbreviaturaTipoMoneda' => 'FJD', 'TipoMoneda' => 'Dólar de Fiji']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 51, 'AbreviaturaTipoMoneda' => 'FKP', 'TipoMoneda' => 'Libra malvinense']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 52, 'AbreviaturaTipoMoneda' => 'GBP', 'TipoMoneda' => 'Libra Esterlina']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 53, 'AbreviaturaTipoMoneda' => 'GEL', 'TipoMoneda' => 'Lari']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 54, 'AbreviaturaTipoMoneda' => 'GHS', 'TipoMoneda' => 'Cedi de Ghana']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 55, 'AbreviaturaTipoMoneda' => 'GIP', 'TipoMoneda' => 'Libra de Gibraltar']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 56, 'AbreviaturaTipoMoneda' => 'GMD', 'TipoMoneda' => 'Dalasi']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 57, 'AbreviaturaTipoMoneda' => 'GNF', 'TipoMoneda' => 'Franco guineano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 58, 'AbreviaturaTipoMoneda' => 'GTQ', 'TipoMoneda' => 'Quetzal']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 59, 'AbreviaturaTipoMoneda' => 'GYD', 'TipoMoneda' => 'Dólar guyanés']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 60, 'AbreviaturaTipoMoneda' => 'HKD', 'TipoMoneda' => 'Dolar De Hong Kong']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 61, 'AbreviaturaTipoMoneda' => 'HNL', 'TipoMoneda' => 'Lempira']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 62, 'AbreviaturaTipoMoneda' => 'HRK', 'TipoMoneda' => 'Kuna']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 63, 'AbreviaturaTipoMoneda' => 'HTG', 'TipoMoneda' => 'Gourde']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 64, 'AbreviaturaTipoMoneda' => 'HUF', 'TipoMoneda' => 'Florín']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 65, 'AbreviaturaTipoMoneda' => 'IDR', 'TipoMoneda' => 'Rupia']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 66, 'AbreviaturaTipoMoneda' => 'ILS', 'TipoMoneda' => 'Nuevo Shekel Israelí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 67, 'AbreviaturaTipoMoneda' => 'INR', 'TipoMoneda' => 'Rupia india']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 68, 'AbreviaturaTipoMoneda' => 'IQD', 'TipoMoneda' => 'Dinar iraquí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 69, 'AbreviaturaTipoMoneda' => 'IRR', 'TipoMoneda' => 'Rial iraní']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 70, 'AbreviaturaTipoMoneda' => 'ISK', 'TipoMoneda' => 'Corona islandesa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 71, 'AbreviaturaTipoMoneda' => 'JMD', 'TipoMoneda' => 'Dólar Jamaiquino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 72, 'AbreviaturaTipoMoneda' => 'JOD', 'TipoMoneda' => 'Dinar jordano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 73, 'AbreviaturaTipoMoneda' => 'JPY', 'TipoMoneda' => 'Yen']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 74, 'AbreviaturaTipoMoneda' => 'KES', 'TipoMoneda' => 'Chelín keniano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 75, 'AbreviaturaTipoMoneda' => 'KGS', 'TipoMoneda' => 'Som']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 76, 'AbreviaturaTipoMoneda' => 'KHR', 'TipoMoneda' => 'Riel']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 77, 'AbreviaturaTipoMoneda' => 'KMF', 'TipoMoneda' => 'Franco Comoro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 78, 'AbreviaturaTipoMoneda' => 'KPW', 'TipoMoneda' => 'Corea del Norte ganó']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 79, 'AbreviaturaTipoMoneda' => 'KRW', 'TipoMoneda' => 'Won']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 80, 'AbreviaturaTipoMoneda' => 'KWD', 'TipoMoneda' => 'Dinar kuwaití']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 81, 'AbreviaturaTipoMoneda' => 'KYD', 'TipoMoneda' => 'Dólar de las Islas Caimán']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 82, 'AbreviaturaTipoMoneda' => 'KZT', 'TipoMoneda' => 'Tenge']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 83, 'AbreviaturaTipoMoneda' => 'LAK', 'TipoMoneda' => 'Kip']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 84, 'AbreviaturaTipoMoneda' => 'LBP', 'TipoMoneda' => 'Libra libanesa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 85, 'AbreviaturaTipoMoneda' => 'LKR', 'TipoMoneda' => 'Rupia de Sri Lanka']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 86, 'AbreviaturaTipoMoneda' => 'LRD', 'TipoMoneda' => 'Dólar liberiano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 87, 'AbreviaturaTipoMoneda' => 'LSL', 'TipoMoneda' => 'Loti']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 88, 'AbreviaturaTipoMoneda' => 'LYD', 'TipoMoneda' => 'Dinar libio']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 89, 'AbreviaturaTipoMoneda' => 'MAD', 'TipoMoneda' => 'Dirham marroquí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 90, 'AbreviaturaTipoMoneda' => 'MDL', 'TipoMoneda' => 'Leu moldavo']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 91, 'AbreviaturaTipoMoneda' => 'MGA', 'TipoMoneda' => 'Ariary malgache']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 92, 'AbreviaturaTipoMoneda' => 'MKD', 'TipoMoneda' => 'Denar']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 93, 'AbreviaturaTipoMoneda' => 'MMK', 'TipoMoneda' => 'Kyat']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 94, 'AbreviaturaTipoMoneda' => 'MNT', 'TipoMoneda' => 'Tugrik']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 95, 'AbreviaturaTipoMoneda' => 'MOP', 'TipoMoneda' => 'Pataca']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 96, 'AbreviaturaTipoMoneda' => 'MRO', 'TipoMoneda' => 'Ouguiya']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 97, 'AbreviaturaTipoMoneda' => 'MUR', 'TipoMoneda' => 'Rupia de Mauricio']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 98, 'AbreviaturaTipoMoneda' => 'MVR', 'TipoMoneda' => 'Rupia']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 99, 'AbreviaturaTipoMoneda' => 'MWK', 'TipoMoneda' => 'Kwacha']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 100, 'AbreviaturaTipoMoneda' => 'MXN', 'TipoMoneda' => 'Peso Mexicano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 101, 'AbreviaturaTipoMoneda' => 'MXV', 'TipoMoneda' => 'México Unidad de Inversión (UDI)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 102, 'AbreviaturaTipoMoneda' => 'MYR', 'TipoMoneda' => 'Ringgit malayo']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 103, 'AbreviaturaTipoMoneda' => 'MZN', 'TipoMoneda' => 'Mozambique Metical']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 104, 'AbreviaturaTipoMoneda' => 'NAD', 'TipoMoneda' => 'Dólar de Namibia']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 105, 'AbreviaturaTipoMoneda' => 'NGN', 'TipoMoneda' => 'Naira']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 106, 'AbreviaturaTipoMoneda' => 'NIO', 'TipoMoneda' => 'Córdoba Oro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 107, 'AbreviaturaTipoMoneda' => 'NOK', 'TipoMoneda' => 'Corona noruega']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 108, 'AbreviaturaTipoMoneda' => 'NPR', 'TipoMoneda' => 'Rupia nepalí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 109, 'AbreviaturaTipoMoneda' => 'NZD', 'TipoMoneda' => 'Dólar de Nueva Zelanda']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 110, 'AbreviaturaTipoMoneda' => 'OMR', 'TipoMoneda' => 'Rial omaní']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 111, 'AbreviaturaTipoMoneda' => 'PAB', 'TipoMoneda' => 'Balboa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 112, 'AbreviaturaTipoMoneda' => 'PEN', 'TipoMoneda' => 'Nuevo Sol']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 113, 'AbreviaturaTipoMoneda' => 'PGK', 'TipoMoneda' => 'Kina']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 114, 'AbreviaturaTipoMoneda' => 'PHP', 'TipoMoneda' => 'Peso filipino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 115, 'AbreviaturaTipoMoneda' => 'PKR', 'TipoMoneda' => 'Rupia de Pakistán']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 116, 'AbreviaturaTipoMoneda' => 'PLN', 'TipoMoneda' => 'Zloty']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 117, 'AbreviaturaTipoMoneda' => 'PYG', 'TipoMoneda' => 'Guaraní']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 118, 'AbreviaturaTipoMoneda' => 'QAR', 'TipoMoneda' => 'Qatar Rial']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 119, 'AbreviaturaTipoMoneda' => 'RON', 'TipoMoneda' => 'Leu rumano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 120, 'AbreviaturaTipoMoneda' => 'RSD', 'TipoMoneda' => 'Dinar serbio']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 121, 'AbreviaturaTipoMoneda' => 'RUB', 'TipoMoneda' => 'Rublo ruso']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 122, 'AbreviaturaTipoMoneda' => 'RWF', 'TipoMoneda' => 'Franco ruandés']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 123, 'AbreviaturaTipoMoneda' => 'SAR', 'TipoMoneda' => 'Riyal saudí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 124, 'AbreviaturaTipoMoneda' => 'SBD', 'TipoMoneda' => 'Dólar de las Islas Salomón']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 125, 'AbreviaturaTipoMoneda' => 'SCR', 'TipoMoneda' => 'Rupia de Seychelles']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 126, 'AbreviaturaTipoMoneda' => 'SDG', 'TipoMoneda' => 'Libra sudanesa']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 127, 'AbreviaturaTipoMoneda' => 'SEK', 'TipoMoneda' => 'Corona sueca']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 128, 'AbreviaturaTipoMoneda' => 'SGD', 'TipoMoneda' => 'Dolar De Singapur']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 129, 'AbreviaturaTipoMoneda' => 'SHP', 'TipoMoneda' => 'Libra de Santa Helena']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 130, 'AbreviaturaTipoMoneda' => 'SLL', 'TipoMoneda' => 'Leona']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 131, 'AbreviaturaTipoMoneda' => 'SOS', 'TipoMoneda' => 'Chelín somalí']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 132, 'AbreviaturaTipoMoneda' => 'SRD', 'TipoMoneda' => 'Dólar de Suriname']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 133, 'AbreviaturaTipoMoneda' => 'SSP', 'TipoMoneda' => 'Libra sudanesa Sur']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 134, 'AbreviaturaTipoMoneda' => 'STD', 'TipoMoneda' => 'Dobra']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 135, 'AbreviaturaTipoMoneda' => 'SVC', 'TipoMoneda' => 'Colon El Salvador']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 136, 'AbreviaturaTipoMoneda' => 'SYP', 'TipoMoneda' => 'Libra Siria']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 137, 'AbreviaturaTipoMoneda' => 'SZL', 'TipoMoneda' => 'Lilangeni']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 138, 'AbreviaturaTipoMoneda' => 'THB', 'TipoMoneda' => 'Baht']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 139, 'AbreviaturaTipoMoneda' => 'TJS', 'TipoMoneda' => 'Somoni']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 140, 'AbreviaturaTipoMoneda' => 'TMT', 'TipoMoneda' => 'Turkmenistán nuevo manat']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 141, 'AbreviaturaTipoMoneda' => 'TND', 'TipoMoneda' => 'Dinar tunecino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 142, 'AbreviaturaTipoMoneda' => 'TOP', 'TipoMoneda' => 'Pa’anga']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 143, 'AbreviaturaTipoMoneda' => 'TRY', 'TipoMoneda' => 'Lira turca']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 144, 'AbreviaturaTipoMoneda' => 'TTD', 'TipoMoneda' => 'Dólar de Trinidad y Tobago']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 145, 'AbreviaturaTipoMoneda' => 'TWD', 'TipoMoneda' => 'Nuevo dólar de Taiwán']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 146, 'AbreviaturaTipoMoneda' => 'TZS', 'TipoMoneda' => 'Shilling tanzano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 147, 'AbreviaturaTipoMoneda' => 'UAH', 'TipoMoneda' => 'Hryvnia']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 148, 'AbreviaturaTipoMoneda' => 'UGX', 'TipoMoneda' => 'Shilling de Uganda']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 149, 'AbreviaturaTipoMoneda' => 'USD', 'TipoMoneda' => 'Dolar americano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 150, 'AbreviaturaTipoMoneda' => 'USN', 'TipoMoneda' => 'Dólar estadounidense (día siguiente)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 151, 'AbreviaturaTipoMoneda' => 'UYI', 'TipoMoneda' => 'Peso Uruguay en Unidades Indexadas (URUIURUI)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 152, 'AbreviaturaTipoMoneda' => 'UYU', 'TipoMoneda' => 'Peso Uruguayo']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 153, 'AbreviaturaTipoMoneda' => 'UZS', 'TipoMoneda' => 'Uzbekistán Sum']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 154, 'AbreviaturaTipoMoneda' => 'VEF', 'TipoMoneda' => 'Bolívar']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 155, 'AbreviaturaTipoMoneda' => 'VND', 'TipoMoneda' => 'Dong']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 156, 'AbreviaturaTipoMoneda' => 'VUV', 'TipoMoneda' => 'Vatu']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 157, 'AbreviaturaTipoMoneda' => 'WST', 'TipoMoneda' => 'Tala']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 158, 'AbreviaturaTipoMoneda' => 'XAF', 'TipoMoneda' => 'Franco CFA BEAC']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 159, 'AbreviaturaTipoMoneda' => 'XAG', 'TipoMoneda' => 'Plata']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 160, 'AbreviaturaTipoMoneda' => 'XAU', 'TipoMoneda' => 'Oro']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 161, 'AbreviaturaTipoMoneda' => 'XBA', 'TipoMoneda' => 'Unidad de Mercados de Bonos Unidad Europea Composite (EURCO)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 162, 'AbreviaturaTipoMoneda' => 'XBB', 'TipoMoneda' => 'Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 163, 'AbreviaturaTipoMoneda' => 'XBC', 'TipoMoneda' => 'Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 164, 'AbreviaturaTipoMoneda' => 'XBD', 'TipoMoneda' => 'Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 165, 'AbreviaturaTipoMoneda' => 'XCD', 'TipoMoneda' => 'Dólar del Caribe Oriental']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 166, 'AbreviaturaTipoMoneda' => 'XDR', 'TipoMoneda' => 'DEG (Derechos Especiales de Giro)']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 167, 'AbreviaturaTipoMoneda' => 'XOF', 'TipoMoneda' => 'Franco CFA BCEAO']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 168, 'AbreviaturaTipoMoneda' => 'XPD', 'TipoMoneda' => 'Paladio']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 169, 'AbreviaturaTipoMoneda' => 'XPF', 'TipoMoneda' => 'Franco CFP']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 170, 'AbreviaturaTipoMoneda' => 'XPT', 'TipoMoneda' => 'Platino']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 171, 'AbreviaturaTipoMoneda' => 'XSU', 'TipoMoneda' => 'Sucre']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 172, 'AbreviaturaTipoMoneda' => 'XTS', 'TipoMoneda' => 'Códigos reservados específicamente para propósitos de prueba']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 173, 'AbreviaturaTipoMoneda' => 'XUA', 'TipoMoneda' => 'Unidad ADB de Cuenta']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 174, 'AbreviaturaTipoMoneda' => 'XXX', 'TipoMoneda' => 'Los códigos asignados para las transacciones en que intervenga ninguna moneda']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 175, 'AbreviaturaTipoMoneda' => 'YER', 'TipoMoneda' => 'Rial yemení']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 176, 'AbreviaturaTipoMoneda' => 'ZAR', 'TipoMoneda' => 'Rand']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 177, 'AbreviaturaTipoMoneda' => 'ZMW', 'TipoMoneda' => 'Kwacha zambiano']);
        DB::table('catalogotipomoneda')->insert(['IdTipoMoneda' => 178, 'AbreviaturaTipoMoneda' => 'ZWL', 'TipoMoneda' => 'Zimbabwe Dólar']);
    }
}
